import { Question } from './types';

// Physics Questions (1-45): Alternating Current, Electromagnetic Waves, Ray Optics & Optical Instruments, Wave Optics
export const physicsQuestions: Question[] = [
  // Alternating Current (1-12)
  { id: 'p1', number: 1, subject: 'PHYSICS', text: 'An alternating voltage V = 200√2 sin(100πt) is applied to a series LCR circuit containing R = 50Ω, L = 0.3 H and C = 20μF. The impedance of the circuit and phase difference between voltage and current are:', options: ['50Ω, tan⁻¹(1)', '50√2 Ω, tan⁻¹(1)', '100Ω, tan⁻¹(2)', '200Ω, tan⁻¹(3)'] },
  { id: 'p2', number: 2, subject: 'PHYSICS', text: 'In an AC circuit, the current is given by i = 5 sin(100t - π/2) ampere and the AC potential is V = 200 sin(100t) volt. The power consumption in the circuit is:', options: ['1000 W', '500 W', '250 W', 'Zero'] },
  { id: 'p3', number: 3, subject: 'PHYSICS', text: 'The power factor of an AC circuit having resistance R and inductance L connected in series to an AC source of angular frequency ω is:', options: ['R/√(R² + ω²L²)', 'ωL/R', 'R/ωL', '√(R² + ω²L²)/R'] },
  { id: 'p4', number: 4, subject: 'PHYSICS', text: 'In a series LCR circuit, the voltage across resistance, inductance and capacitance are 10 V, 10 V and 10 V respectively. The voltage across the LCR combination will be:', options: ['10 V', '10√3 V', '20 V', '30 V'] },
  { id: 'p5', number: 5, subject: 'PHYSICS', text: 'At resonance in a series LCR circuit, which of the following statements is correct?', options: ['Current is minimum', 'Impedance is maximum', 'Current and voltage are in phase', 'Power factor is zero'] },
  { id: 'p6', number: 6, subject: 'PHYSICS', text: 'A capacitor of capacitance C is connected to an AC source of voltage V = V₀ sin(ωt). The current in the circuit is:', options: ['V₀ωC cos(ωt)', 'V₀ωC sin(ωt)', '(V₀/ωC) cos(ωt)', '(V₀/ωC) sin(ωt)'] },
  { id: 'p7', number: 7, subject: 'PHYSICS', text: 'The quality factor Q of a series LCR circuit with L = 2.0 H, C = 2μF and R = 10Ω is:', options: ['100', '200', '50', '25'] },
  { id: 'p8', number: 8, subject: 'PHYSICS', text: 'In a transformer, the number of turns in the primary coil is 500 and that in the secondary coil is 5000. If the primary voltage is 20 V, the secondary voltage is:', options: ['200 V', '2 V', '2000 V', '0.2 V'] },
  { id: 'p9', number: 9, subject: 'PHYSICS', text: 'The RMS value of an AC voltage given by V = 100 sin(314t) + 50 sin(628t) is:', options: ['√6250 V', '75 V', '150 V', '100 V'] },
  { id: 'p10', number: 10, subject: 'PHYSICS', text: 'An AC source of angular frequency ω is fed across a resistor R and a capacitor C in series. The current registered is I. If now the frequency of source is changed to ω/3, the current in the circuit is:', options: ['Greater than I', 'Less than I', 'Equal to I', 'Depends on R and C values'] },
  { id: 'p11', number: 11, subject: 'PHYSICS', text: 'A choke coil of negligible resistance carries 5 mA current when connected to a 220 V, 50 Hz AC supply. The inductance of the coil is approximately:', options: ['140 H', '1.4 H', '14 H', '0.14 H'] },
  { id: 'p12', number: 12, subject: 'PHYSICS', text: 'In a series LCR circuit, the voltages across an inductor, a capacitor and a resistor are 30 V, 30 V and 60 V respectively. The phase difference between the applied voltage and the current is:', options: ['0°', '30°', '45°', '60°'] },
  // Electromagnetic Waves (13-24)
  { id: 'p13', number: 13, subject: 'PHYSICS', text: 'An electromagnetic wave travelling in the positive x-direction has wavelength 5 mm. The electric field amplitude is 66 V/m in y-direction. The magnitude of magnetic field amplitude is:', options: ['2.2 × 10⁻⁷ T', '1.1 × 10⁻⁷ T', '3.3 × 10⁻⁷ T', '4.4 × 10⁻⁷ T'] },
  { id: 'p14', number: 14, subject: 'PHYSICS', text: 'Which of the following electromagnetic radiation has the smallest wavelength?', options: ['X-rays', 'Gamma rays', 'Ultraviolet rays', 'Microwaves'] },
  { id: 'p15', number: 15, subject: 'PHYSICS', text: 'The electric field in an electromagnetic wave is given by E = 50 sin ω(t - x/c). The energy contained in a cylinder of cross section 10 cm² and length 50 cm along the x-axis is:', options: ['5.5 × 10⁻¹² J', '1.1 × 10⁻¹¹ J', '2.2 × 10⁻¹¹ J', '4.4 × 10⁻¹¹ J'] },
  { id: 'p16', number: 16, subject: 'PHYSICS', text: 'The frequency of electromagnetic wave which is best suited to observe a particle of radius 3 × 10⁻⁴ cm is of the order of:', options: ['10¹⁵ Hz', '10¹⁴ Hz', '10¹³ Hz', '10¹² Hz'] },
  { id: 'p17', number: 17, subject: 'PHYSICS', text: 'The electromagnetic radiation used for killing germs in water purifiers is:', options: ['Infrared radiation', 'Ultraviolet radiation', 'Microwaves', 'Radio waves'] },
  { id: 'p18', number: 18, subject: 'PHYSICS', text: 'According to Maxwell\'s hypothesis, a changing electric field produces:', options: ['An electric field', 'A magnetic field', 'Both electric and magnetic fields', 'Neither electric nor magnetic field'] },
  { id: 'p19', number: 19, subject: 'PHYSICS', text: 'The ratio of amplitude of magnetic field to the amplitude of electric field for an electromagnetic wave propagating in vacuum is equal to:', options: ['The speed of light in vacuum', 'Reciprocal of speed of light in vacuum', 'The ratio of magnetic permeability to electric permittivity of vacuum', 'Unity'] },
  { id: 'p20', number: 20, subject: 'PHYSICS', text: 'Ozone layer blocks the radiation of wavelength:', options: ['Less than 3 × 10⁻⁷ m', 'Greater than 3 × 10⁻⁷ m', 'Equal to 3 × 10⁻⁷ m', 'Between 10⁻⁷ m and 10⁻⁶ m'] },
  { id: 'p21', number: 21, subject: 'PHYSICS', text: 'The pressure exerted by electromagnetic wave of intensity I on a perfectly reflecting surface is:', options: ['I/c', '2I/c', 'I/2c', 'I/c²'] },
  { id: 'p22', number: 22, subject: 'PHYSICS', text: 'In electromagnetic waves, the phase difference between electric and magnetic field vectors is:', options: ['0', 'π/2', 'π', 'π/4'] },
  { id: 'p23', number: 23, subject: 'PHYSICS', text: 'Which of the following is NOT a characteristic of electromagnetic waves?', options: ['They require a medium for propagation', 'They travel at the speed of light in vacuum', 'Electric and magnetic fields are perpendicular', 'They carry energy and momentum'] },
  { id: 'p24', number: 24, subject: 'PHYSICS', text: 'The displacement current was introduced by:', options: ['Faraday', 'Maxwell', 'Hertz', 'Ampere'] },
  // Ray Optics & Optical Instruments (25-36)
  { id: 'p25', number: 25, subject: 'PHYSICS', text: 'A convex lens of focal length 20 cm and a concave lens of focal length 10 cm are placed coaxially 20 cm apart. An object at 60 cm from convex lens forms final image at:', options: ['10 cm on object side', '20 cm on object side', '30 cm opposite to object', '15 cm opposite to object'] },
  { id: 'p26', number: 26, subject: 'PHYSICS', text: 'The critical angle for total internal reflection for a ray going from glass (μ = 1.5) to water (μ = 1.33) is:', options: ['sin⁻¹(0.89)', 'sin⁻¹(0.67)', 'sin⁻¹(1.13)', 'sin⁻¹(0.5)'] },
  { id: 'p27', number: 27, subject: 'PHYSICS', text: 'A person can see objects clearly from 25 cm to infinity. The power of spectacles required to read a book at a distance of 10 cm is:', options: ['+6 D', '+4 D', '-6 D', '-4 D'] },
  { id: 'p28', number: 28, subject: 'PHYSICS', text: 'The focal length of a convex lens is 10 cm. What is the power of the lens in diopters?', options: ['10 D', '0.1 D', '100 D', '1 D'] },
  { id: 'p29', number: 29, subject: 'PHYSICS', text: 'A ray of light passes from air to glass (μ = 1.5) at an angle of 30°. The angle of refraction is:', options: ['sin⁻¹(1/3)', 'sin⁻¹(1/2)', 'sin⁻¹(2/3)', 'sin⁻¹(3/4)'] },
  { id: 'p30', number: 30, subject: 'PHYSICS', text: 'Two thin lenses of focal lengths f₁ and f₂ are in contact. The power of the combination is:', options: ['1/f₁ + 1/f₂', 'f₁ + f₂', 'f₁f₂/(f₁ + f₂)', '1/(f₁ + f₂)'] },
  { id: 'p31', number: 31, subject: 'PHYSICS', text: 'In a compound microscope, the magnifying power is 95 and the focal length of objective is 5 cm. If the final image is formed at 25 cm from the eye, the focal length of eye-piece is:', options: ['5 cm', '10 cm', '15 cm', '20 cm'] },
  { id: 'p32', number: 32, subject: 'PHYSICS', text: 'A concave mirror forms a real image 3 times the size of the object. If the object distance is 20 cm, the focal length of the mirror is:', options: ['15 cm', '10 cm', '20 cm', '30 cm'] },
  { id: 'p33', number: 33, subject: 'PHYSICS', text: 'The refractive index of a prism is √2 and its refracting angle is 60°. The minimum angle of deviation is:', options: ['30°', '45°', '60°', '90°'] },
  { id: 'p34', number: 34, subject: 'PHYSICS', text: 'An astronomical telescope has an objective of focal length 200 cm and an eyepiece of focal length 4 cm. The magnifying power of the telescope in normal adjustment is:', options: ['50', '100', '200', '25'] },
  { id: 'p35', number: 35, subject: 'PHYSICS', text: 'A glass slab of thickness 4 cm contains the same number of waves as 5 cm of water when both are traversed by the same monochromatic light. If refractive index of water is 4/3, the refractive index of glass is:', options: ['5/3', '4/3', '16/9', '3/2'] },
  { id: 'p36', number: 36, subject: 'PHYSICS', text: 'The image formed by a concave mirror is real, inverted and of the same size as the object. The position of the object is:', options: ['At the focus', 'At the centre of curvature', 'Between focus and centre of curvature', 'Beyond centre of curvature'] },
  // Wave Optics (37-45)
  { id: 'p37', number: 37, subject: 'PHYSICS', text: 'In Young\'s double slit experiment, the slits are 0.28 mm apart and the screen is 1.4 m away. The distance between central bright fringe and fourth bright fringe is 1.2 cm. The wavelength is:', options: ['600 nm', '500 nm', '450 nm', '400 nm'] },
  { id: 'p38', number: 38, subject: 'PHYSICS', text: 'In Young\'s double slit experiment, if the separation between the slits is halved and the distance between the slits and screen is doubled, the fringe width:', options: ['Remains unchanged', 'Becomes half', 'Becomes four times', 'Becomes double'] },
  { id: 'p39', number: 39, subject: 'PHYSICS', text: 'The phenomenon of interference is shown by:', options: ['Longitudinal mechanical waves only', 'Transverse mechanical waves only', 'Electromagnetic waves only', 'All types of waves'] },
  { id: 'p40', number: 40, subject: 'PHYSICS', text: 'In a single slit diffraction pattern, the width of central maximum is twice the angular width of:', options: ['First secondary maximum', 'Second secondary maximum', 'First secondary minimum', 'Any secondary maximum'] },
  { id: 'p41', number: 41, subject: 'PHYSICS', text: 'According to Huygens principle, every point on a wavefront acts as:', options: ['A source of secondary wavelets', 'A reflector', 'An absorber', 'A polarizer'] },
  { id: 'p42', number: 42, subject: 'PHYSICS', text: 'When light is polarized by reflection, the angle between reflected and refracted rays is:', options: ['45°', '60°', '90°', '180°'] },
  { id: 'p43', number: 43, subject: 'PHYSICS', text: 'The intensity ratio of maxima and minima in an interference pattern is 25:9. The ratio of amplitudes of the two interfering waves is:', options: ['5:3', '25:9', '4:1', '9:4'] },
  { id: 'p44', number: 44, subject: 'PHYSICS', text: 'In Young\'s double slit experiment, if white light is used, then the central fringe will be:', options: ['Red', 'Violet', 'White', 'Black'] },
  { id: 'p45', number: 45, subject: 'PHYSICS', text: 'The resolving power of a microscope depends on:', options: ['The wavelength of light and numerical aperture', 'The focal length of objective only', 'The focal length of eyepiece only', 'The distance between slits'] },
];

// Chemistry Questions (46-90): Amines, d & f Block Elements, Coordination Compounds
export const chemistryQuestions: Question[] = [
  // Amines (46-60)
  { id: 'c1', number: 46, subject: 'CHEMISTRY', text: 'The correct order of basic strength among the following amines is:', options: ['C₂H₅NH₂ > (C₂H₅)₂NH > (C₂H₅)₃N > NH₃', '(C₂H₅)₂NH > C₂H₅NH₂ > (C₂H₅)₃N > NH₃', 'NH₃ > C₂H₅NH₂ > (C₂H₅)₂NH > (C₂H₅)₃N', '(C₂H₅)₃N > (C₂H₅)₂NH > C₂H₅NH₂ > NH₃'] },
  { id: 'c2', number: 47, subject: 'CHEMISTRY', text: 'Which of the following compounds will give positive carbylamine test?', options: ['N,N-Dimethylaniline', 'N-Methylaniline', 'Aniline', 'Triethylamine'] },
  { id: 'c3', number: 48, subject: 'CHEMISTRY', text: 'Hinsberg\'s reagent is:', options: ['C₆H₅SO₂Cl', 'C₆H₅COCl', 'C₆H₅CHO', 'C₆H₅NH₂'] },
  { id: 'c4', number: 49, subject: 'CHEMISTRY', text: 'The product formed when aniline reacts with bromine water is:', options: ['o-bromoaniline', 'm-bromoaniline', 'p-bromoaniline', '2,4,6-tribromoaniline'] },
  { id: 'c5', number: 50, subject: 'CHEMISTRY', text: 'Gabriel phthalimide synthesis is used for the preparation of:', options: ['Primary aliphatic amines', 'Secondary amines', 'Tertiary amines', 'Aromatic amines'] },
  { id: 'c6', number: 51, subject: 'CHEMISTRY', text: 'In the reaction of aniline with HNO₂ at 0-5°C, the product formed is:', options: ['Nitrosobenzene', 'Nitrobenzene', 'Benzenediazonium chloride', 'Phenol'] },
  { id: 'c7', number: 52, subject: 'CHEMISTRY', text: 'The correct IUPAC name of the compound (CH₃)₂CHNH₂ is:', options: ['Isopropylamine', 'Propan-2-amine', '2-Aminopropane', 'Both (2) and (3)'] },
  { id: 'c8', number: 53, subject: 'CHEMISTRY', text: 'Which of the following is the most basic amine in aqueous solution?', options: ['Aniline', 'Methylamine', 'Dimethylamine', 'Trimethylamine'] },
  { id: 'c9', number: 54, subject: 'CHEMISTRY', text: 'Aniline does not undergo Friedel-Crafts reaction because:', options: ['The catalyst AlCl₃ reacts with amine group', 'The ring gets deactivated', 'Aniline is unstable', 'None of the above'] },
  { id: 'c10', number: 55, subject: 'CHEMISTRY', text: 'The reaction of primary amine with chloroform and alcoholic KOH is called:', options: ['Hoffmann bromamide reaction', 'Carbylamine reaction', 'Gabriel synthesis', 'Coupling reaction'] },
  { id: 'c11', number: 56, subject: 'CHEMISTRY', text: 'Which of the following will not give Hoffmann bromamide degradation?', options: ['CH₃CONH₂', 'C₆H₅CONH₂', 'CH₃CONHCH₃', '(CH₃)₂CHCONH₂'] },
  { id: 'c12', number: 57, subject: 'CHEMISTRY', text: 'Reduction of nitrobenzene by which reagent gives aniline?', options: ['Zn/NaOH', 'Sn/HCl', 'LiAlH₄/ether', 'Na/C₂H₅OH'] },
  { id: 'c13', number: 58, subject: 'CHEMISTRY', text: 'Aniline on reaction with acetyl chloride gives:', options: ['Acetanilide', 'Aniline hydrochloride', 'p-aminoacetophenone', 'None of these'] },
  { id: 'c14', number: 59, subject: 'CHEMISTRY', text: 'The compound which undergoes diazotization most readily is:', options: ['p-Nitroaniline', 'Aniline', 'p-Toluidine', 'p-Methoxyaniline'] },
  { id: 'c15', number: 60, subject: 'CHEMISTRY', text: 'Which reagent converts nitrobenzene to azobenzene?', options: ['Sn/HCl', 'Zn/NH₄Cl', 'LiAlH₄', 'Zn/NaOH'] },
  // d & f Block Elements (61-75)
  { id: 'c16', number: 61, subject: 'CHEMISTRY', text: 'Which of the following transition metal ions is colourless?', options: ['Cu²⁺', 'Fe²⁺', 'Zn²⁺', 'Ni²⁺'] },
  { id: 'c17', number: 62, subject: 'CHEMISTRY', text: 'The electronic configuration of Cr (Z = 24) is:', options: ['[Ar] 3d⁵ 4s¹', '[Ar] 3d⁴ 4s²', '[Ar] 3d⁶ 4s⁰', '[Ar] 3d³ 4s² 4p¹'] },
  { id: 'c18', number: 63, subject: 'CHEMISTRY', text: 'Which of the following shows maximum number of oxidation states?', options: ['V', 'Cr', 'Mn', 'Fe'] },
  { id: 'c19', number: 64, subject: 'CHEMISTRY', text: 'The element with highest first ionization enthalpy in 3d series is:', options: ['Sc', 'Ti', 'Zn', 'Cu'] },
  { id: 'c20', number: 65, subject: 'CHEMISTRY', text: 'Lanthanide contraction is due to:', options: ['Poor shielding effect of 4f electrons', 'Effective shielding of 5d electrons', 'Poor shielding effect of 5d electrons', 'Effective shielding of 4f electrons'] },
  { id: 'c21', number: 66, subject: 'CHEMISTRY', text: 'Which of the following is used in photography?', options: ['AgBr', 'AgCl', 'AgI', 'AgNO₃'] },
  { id: 'c22', number: 67, subject: 'CHEMISTRY', text: 'The pair of lanthanides in which both elements have 4f⁷ configuration is:', options: ['Eu, Gd', 'Eu, Tb', 'Gd, Tb', 'Sm, Eu'] },
  { id: 'c23', number: 68, subject: 'CHEMISTRY', text: 'KMnO₄ acts as an oxidizing agent in acidic medium. The change in oxidation state of Mn is:', options: ['+7 to +2', '+7 to +4', '+7 to +6', '+7 to 0'] },
  { id: 'c24', number: 69, subject: 'CHEMISTRY', text: 'Which of the following transition metals has the highest density?', options: ['Os', 'Ir', 'Pt', 'Au'] },
  { id: 'c25', number: 70, subject: 'CHEMISTRY', text: 'The color of K₂Cr₂O₇ is:', options: ['Yellow', 'Orange', 'Green', 'Blue'] },
  { id: 'c26', number: 71, subject: 'CHEMISTRY', text: 'Which among the following is the strongest reducing agent?', options: ['Fe²⁺', 'Cr²⁺', 'V²⁺', 'Ti²⁺'] },
  { id: 'c27', number: 72, subject: 'CHEMISTRY', text: 'The actinoid element which does not show +3 oxidation state is:', options: ['Th', 'U', 'Np', 'Pu'] },
  { id: 'c28', number: 73, subject: 'CHEMISTRY', text: 'The magnetic moment of a transition metal ion is 3.87 BM. The number of unpaired electrons in the ion is:', options: ['2', '3', '4', '1'] },
  { id: 'c29', number: 74, subject: 'CHEMISTRY', text: 'Which of the following metals forms an interstitial compound with hydrogen?', options: ['Na', 'Pd', 'Ca', 'Mg'] },
  { id: 'c30', number: 75, subject: 'CHEMISTRY', text: 'The element commonly used as a catalyst in Haber\'s process for manufacture of ammonia is:', options: ['Vanadium', 'Iron', 'Platinum', 'Nickel'] },
  // Coordination Compounds (76-90)
  { id: 'c31', number: 76, subject: 'CHEMISTRY', text: 'The IUPAC name of [Pt(NH₃)₂Cl(NO₂)] is:', options: ['Platinum diaminechloronitrite', 'Diamminechloronitrito-N-platinum(II)', 'Diamminechloridonitrito-N-platinum(II)', 'Chlorodiamminenitritoplatinate(II)'] },
  { id: 'c32', number: 77, subject: 'CHEMISTRY', text: 'The coordination number and oxidation state of Cr in K₃[Cr(C₂O₄)₃] are respectively:', options: ['6 and +3', '3 and +3', '4 and +2', '6 and +2'] },
  { id: 'c33', number: 78, subject: 'CHEMISTRY', text: 'Which of the following complex ions is diamagnetic?', options: ['[Ni(CN)₄]²⁻', '[NiCl₄]²⁻', '[CoF₆]³⁻', '[Cu(NH₃)₄]²⁺'] },
  { id: 'c34', number: 79, subject: 'CHEMISTRY', text: 'The type of isomerism exhibited by [Co(NH₃)₅Br]SO₄ and [Co(NH₃)₅SO₄]Br is:', options: ['Geometrical isomerism', 'Ionization isomerism', 'Linkage isomerism', 'Coordination isomerism'] },
  { id: 'c35', number: 80, subject: 'CHEMISTRY', text: 'According to Crystal Field Theory, the splitting of d-orbitals in an octahedral complex gives:', options: ['t₂g (lower) and eg (higher)', 'eg (lower) and t₂g (higher)', 'All five d-orbitals at same energy', 't₂g (higher) and eg (lower)'] },
  { id: 'c36', number: 81, subject: 'CHEMISTRY', text: 'Which of the following ligands is a chelating ligand?', options: ['H₂O', 'NH₃', 'en (ethylenediamine)', 'CO'] },
  { id: 'c37', number: 82, subject: 'CHEMISTRY', text: 'The hybridization of Fe in [Fe(CN)₆]⁴⁻ is:', options: ['sp³d²', 'd²sp³', 'sp³d', 'dsp³'] },
  { id: 'c38', number: 83, subject: 'CHEMISTRY', text: 'Which of the following has the highest value of crystal field stabilization energy (CFSE)?', options: ['[Co(CN)₆]³⁻', '[CoF₆]³⁻', '[Co(H₂O)₆]³⁺', '[Co(NH₃)₆]³⁺'] },
  { id: 'c39', number: 84, subject: 'CHEMISTRY', text: 'The shape of [Ni(CO)₄] is:', options: ['Square planar', 'Tetrahedral', 'Octahedral', 'Trigonal bipyramidal'] },
  { id: 'c40', number: 85, subject: 'CHEMISTRY', text: 'A complex [MA₃B₃] showing geometrical isomerism is likely to have:', options: ['Tetrahedral geometry', 'Octahedral geometry', 'Square planar geometry', 'Linear geometry'] },
  { id: 'c41', number: 86, subject: 'CHEMISTRY', text: 'EAN (Effective Atomic Number) of Fe in [Fe(CN)₆]⁴⁻ is:', options: ['36', '34', '26', '30'] },
  { id: 'c42', number: 87, subject: 'CHEMISTRY', text: 'Among the following complexes, the one which shows optical isomerism is:', options: ['cis-[Co(en)₂Cl₂]⁺', 'trans-[Co(en)₂Cl₂]⁺', '[Co(NH₃)₄Cl₂]⁺', '[Pt(NH₃)₂Cl₂]'] },
  { id: 'c43', number: 88, subject: 'CHEMISTRY', text: 'Which of the following is an example of a neutral ligand?', options: ['Cl⁻', 'OH⁻', 'CO', 'CN⁻'] },
  { id: 'c44', number: 89, subject: 'CHEMISTRY', text: 'The spin-only magnetic moment of [MnBr₄]²⁻ is:', options: ['5.92 BM', '4.90 BM', '3.87 BM', '2.83 BM'] },
  { id: 'c45', number: 90, subject: 'CHEMISTRY', text: 'Which of the following complexes will have the maximum molar conductivity?', options: ['[Co(NH₃)₆]Cl₃', '[Co(NH₃)₅Cl]Cl₂', '[Co(NH₃)₄Cl₂]Cl', '[Co(NH₃)₃Cl₃]'] },
];

// Zoology Questions (91-135): Molecular Basis of Inheritance II, Evolution, Human Health & Diseases
export const zoologyQuestions: Question[] = [
  // Molecular Basis of Inheritance II (91-110)
  { id: 'z1', number: 91, subject: 'ZOOLOGY', text: 'The enzyme responsible for the synthesis of RNA primer during DNA replication is:', options: ['DNA polymerase III', 'Primase', 'Helicase', 'Ligase'] },
  { id: 'z2', number: 92, subject: 'ZOOLOGY', text: 'During transcription, the sigma factor is associated with:', options: ['Initiation', 'Elongation', 'Termination', 'All of the above'] },
  { id: 'z3', number: 93, subject: 'ZOOLOGY', text: 'The technique used for separation of DNA fragments based on their size is:', options: ['PCR', 'Gel electrophoresis', 'ELISA', 'Southern blotting'] },
  { id: 'z4', number: 94, subject: 'ZOOLOGY', text: 'Which of the following is NOT a component of the lac operon?', options: ['Promoter', 'Operator', 'Structural genes', 'Enhancer'] },
  { id: 'z5', number: 95, subject: 'ZOOLOGY', text: 'The process by which genetic information flows from DNA to RNA to protein is called:', options: ['Translation', 'Transcription', 'Central dogma', 'Replication'] },
  { id: 'z6', number: 96, subject: 'ZOOLOGY', text: 'DNA fingerprinting involves identification of differences in:', options: ['Satellite DNA', 'Bulk DNA', 'rDNA', 'mRNA'] },
  { id: 'z7', number: 97, subject: 'ZOOLOGY', text: 'Wobble hypothesis was proposed by:', options: ['Watson and Crick', 'Francis Crick', 'Beadle and Tatum', 'Har Gobind Khorana'] },
  { id: 'z8', number: 98, subject: 'ZOOLOGY', text: 'The amino acid coded by the codon AUG is:', options: ['Valine', 'Methionine', 'Leucine', 'Tryptophan'] },
  { id: 'z9', number: 99, subject: 'ZOOLOGY', text: 'Human genome has approximately how many genes?', options: ['20,000-25,000', '50,000-60,000', '100,000-150,000', '10,000-15,000'] },
  { id: 'z10', number: 100, subject: 'ZOOLOGY', text: 'The mRNA has a sequence of 900 nucleotides. The number of amino acids in the polypeptide chain synthesized will be:', options: ['300', '299', '900', '450'] },
  { id: 'z11', number: 101, subject: 'ZOOLOGY', text: 'Splicing of mRNA occurs in:', options: ['Cytoplasm', 'Nucleus', 'Ribosome', 'Mitochondria'] },
  { id: 'z12', number: 102, subject: 'ZOOLOGY', text: 'The enzyme that joins Okazaki fragments during DNA replication is:', options: ['DNA ligase', 'DNA polymerase I', 'Helicase', 'Topoisomerase'] },
  { id: 'z13', number: 103, subject: 'ZOOLOGY', text: 'Satellite DNA is useful in DNA fingerprinting because it shows:', options: ['High degree of polymorphism', 'No variation in population', 'Same sequence in all individuals', 'Expression in all cells'] },
  { id: 'z14', number: 104, subject: 'ZOOLOGY', text: 'The enzyme that unwinds the DNA double helix during replication is:', options: ['Topoisomerase', 'Helicase', 'Primase', 'Ligase'] },
  { id: 'z15', number: 105, subject: 'ZOOLOGY', text: 'Which of the following is a stop codon?', options: ['AUG', 'UAA', 'GGG', 'CCC'] },
  { id: 'z16', number: 106, subject: 'ZOOLOGY', text: 'In eukaryotes, the mRNA undergoes splicing to remove:', options: ['Exons', 'Introns', 'Promoter', 'Enhancer'] },
  { id: 'z17', number: 107, subject: 'ZOOLOGY', text: 'The number of hydrogen bonds between adenine and thymine is:', options: ['2', '3', '4', '1'] },
  { id: 'z18', number: 108, subject: 'ZOOLOGY', text: 'Taylor\'s experiment on Vicia faba proved:', options: ['DNA is genetic material', 'DNA replication is semi-conservative', 'Transcription occurs in nucleus', 'Translation occurs on ribosomes'] },
  { id: 'z19', number: 109, subject: 'ZOOLOGY', text: 'RNA polymerase in prokaryotes requires which factor for termination?', options: ['Sigma factor', 'Rho factor', 'TATA factor', 'Release factor'] },
  { id: 'z20', number: 110, subject: 'ZOOLOGY', text: 'The technique used to amplify specific DNA sequences is:', options: ['Southern blotting', 'Northern blotting', 'PCR', 'RFLP'] },
  // Evolution (111-120)
  { id: 'z21', number: 111, subject: 'ZOOLOGY', text: 'The book "Origin of Species" was written by:', options: ['Lamarck', 'Darwin', 'Wallace', 'Mendel'] },
  { id: 'z22', number: 112, subject: 'ZOOLOGY', text: 'Homologous organs indicate:', options: ['Convergent evolution', 'Divergent evolution', 'Parallel evolution', 'Co-evolution'] },
  { id: 'z23', number: 113, subject: 'ZOOLOGY', text: 'The wings of insects and birds are:', options: ['Homologous organs', 'Analogous organs', 'Vestigial organs', 'Rudimentary organs'] },
  { id: 'z24', number: 114, subject: 'ZOOLOGY', text: 'Hardy-Weinberg equilibrium is affected by:', options: ['Gene flow', 'Genetic drift', 'Natural selection', 'All of the above'] },
  { id: 'z25', number: 115, subject: 'ZOOLOGY', text: 'The phenomenon of industrial melanism demonstrates:', options: ['Mutation', 'Natural selection', 'Genetic drift', 'Gene flow'] },
  { id: 'z26', number: 116, subject: 'ZOOLOGY', text: 'Fossil evidence of human evolution was first found in:', options: ['Africa', 'Europe', 'Asia', 'Australia'] },
  { id: 'z27', number: 117, subject: 'ZOOLOGY', text: 'Miller and Urey experiment demonstrated:', options: ['Origin of life', 'Abiotic synthesis of organic molecules', 'Biogenesis', 'Spontaneous generation'] },
  { id: 'z28', number: 118, subject: 'ZOOLOGY', text: 'Genetic drift operates in:', options: ['Large populations', 'Small populations', 'Infinite populations', 'All populations equally'] },
  { id: 'z29', number: 119, subject: 'ZOOLOGY', text: 'The first cellular form of life appeared on Earth about:', options: ['2000 million years ago', '3500 million years ago', '1000 million years ago', '500 million years ago'] },
  { id: 'z30', number: 120, subject: 'ZOOLOGY', text: 'Speciation that occurs due to geographical isolation is called:', options: ['Sympatric speciation', 'Allopatric speciation', 'Parapatric speciation', 'Peripatric speciation'] },
  // Human Health & Diseases (121-135)
  { id: 'z31', number: 121, subject: 'ZOOLOGY', text: 'The causative agent of typhoid is:', options: ['Streptococcus', 'Salmonella typhi', 'Vibrio cholerae', 'Shigella'] },
  { id: 'z32', number: 122, subject: 'ZOOLOGY', text: 'Widal test is used for diagnosis of:', options: ['Malaria', 'Typhoid', 'Pneumonia', 'AIDS'] },
  { id: 'z33', number: 123, subject: 'ZOOLOGY', text: 'Plasmodium vivax causes:', options: ['Malignant malaria', 'Benign tertian malaria', 'Quartan malaria', 'Ovale malaria'] },
  { id: 'z34', number: 124, subject: 'ZOOLOGY', text: 'The vector for dengue fever is:', options: ['Anopheles mosquito', 'Aedes mosquito', 'Culex mosquito', 'Sand fly'] },
  { id: 'z35', number: 125, subject: 'ZOOLOGY', text: 'AIDS is caused by:', options: ['Bacterium', 'Retrovirus', 'Protozoan', 'Fungus'] },
  { id: 'z36', number: 126, subject: 'ZOOLOGY', text: 'Which cells are primarily attacked by HIV?', options: ['B-lymphocytes', 'T-helper cells', 'T-cytotoxic cells', 'Macrophages only'] },
  { id: 'z37', number: 127, subject: 'ZOOLOGY', text: 'ELISA test is used for the detection of:', options: ['Typhoid', 'Cancer', 'AIDS', 'Tuberculosis'] },
  { id: 'z38', number: 128, subject: 'ZOOLOGY', text: 'Interferon is:', options: ['Antiviral protein', 'Antibody', 'Antigen', 'Antibiotic'] },
  { id: 'z39', number: 129, subject: 'ZOOLOGY', text: 'Cancer cells are characterized by:', options: ['Contact inhibition', 'Controlled division', 'Uncontrolled division', 'Apoptosis'] },
  { id: 'z40', number: 130, subject: 'ZOOLOGY', text: 'Oncogenes are:', options: ['Tumor suppressor genes', 'Genes causing cancer', 'Normal genes', 'Viral genes only'] },
  { id: 'z41', number: 131, subject: 'ZOOLOGY', text: 'DPT vaccine provides immunity against:', options: ['Diphtheria, Pertussis, Tetanus', 'Dengue, Polio, Typhoid', 'Diphtheria, Polio, TB', 'Dengue, Pertussis, TB'] },
  { id: 'z42', number: 132, subject: 'ZOOLOGY', text: 'Active immunity is developed when:', options: ['Ready-made antibodies are injected', 'Antigens enter the body', 'Antibodies are passed through placenta', 'Antibodies are received through mother\'s milk'] },
  { id: 'z43', number: 133, subject: 'ZOOLOGY', text: 'Which of the following is an autoimmune disease?', options: ['AIDS', 'Rheumatoid arthritis', 'Malaria', 'Tuberculosis'] },
  { id: 'z44', number: 134, subject: 'ZOOLOGY', text: 'The drug obtained from Papaver somniferum is:', options: ['Cocaine', 'Morphine', 'Marijuana', 'LSD'] },
  { id: 'z45', number: 135, subject: 'ZOOLOGY', text: 'Benign tumors are:', options: ['Cancerous', 'Non-cancerous', 'Fast spreading', 'Metastatic'] },
];

// Botany Questions (136-180): Microbes in Human Welfare, Organisms and Populations
export const botanyQuestions: Question[] = [
  // Microbes in Human Welfare (136-160)
  { id: 'b1', number: 136, subject: 'BOTANY', text: 'The microbe used in the production of Swiss cheese is:', options: ['Lactobacillus', 'Propionibacterium shermanii', 'Streptococcus thermophilus', 'Aspergillus niger'] },
  { id: 'b2', number: 137, subject: 'BOTANY', text: 'Cyclosporin A, an immunosuppressant, is obtained from:', options: ['Trichoderma polysporum', 'Monascus purpureus', 'Penicillium notatum', 'Aspergillus niger'] },
  { id: 'b3', number: 138, subject: 'BOTANY', text: 'The gas produced during the treatment of sewage in secondary treatment is:', options: ['Oxygen', 'Nitrogen', 'Methane', 'Carbon dioxide'] },
  { id: 'b4', number: 139, subject: 'BOTANY', text: 'BOD of waste water is a measure of:', options: ['Industrial pollutants', 'Organic matter', 'Inorganic matter', 'Sediments'] },
  { id: 'b5', number: 140, subject: 'BOTANY', text: 'Which microorganism is used for the production of ethanol from molasses?', options: ['Saccharomyces cerevisiae', 'Aspergillus niger', 'Lactobacillus', 'Clostridium'] },
  { id: 'b6', number: 141, subject: 'BOTANY', text: 'Statins used as blood cholesterol lowering agents are produced by:', options: ['Trichoderma', 'Monascus purpureus', 'Penicillium', 'Streptococcus'] },
  { id: 'b7', number: 142, subject: 'BOTANY', text: 'The cry genes encoding Bt toxin are present in:', options: ['Bacillus thuringiensis', 'E. coli', 'Agrobacterium', 'Pseudomonas'] },
  { id: 'b8', number: 143, subject: 'BOTANY', text: 'Which of the following is used as a biocontrol agent against plant diseases?', options: ['Bacillus thuringiensis', 'Trichoderma', 'Baculovirus', 'All of the above'] },
  { id: 'b9', number: 144, subject: 'BOTANY', text: 'Mycorrhiza is a symbiotic association between:', options: ['Algae and fungi', 'Fungi and plant roots', 'Bacteria and plant roots', 'Two species of fungi'] },
  { id: 'b10', number: 145, subject: 'BOTANY', text: 'The primary treatment of sewage involves:', options: ['Biological treatment', 'Physical removal of particles', 'Chemical treatment', 'Chlorination'] },
  { id: 'b11', number: 146, subject: 'BOTANY', text: 'Penicillin was discovered by:', options: ['Alexander Fleming', 'Ernst Chain', 'Howard Florey', 'Louis Pasteur'] },
  { id: 'b12', number: 147, subject: 'BOTANY', text: 'Curd formation from milk involves:', options: ['Lactobacillus', 'Streptococcus', 'Acetobacter', 'Clostridium'] },
  { id: 'b13', number: 148, subject: 'BOTANY', text: 'Gobar gas is produced by:', options: ['Aerobic bacteria', 'Methanogenic bacteria', 'Nitrifying bacteria', 'Denitrifying bacteria'] },
  { id: 'b14', number: 149, subject: 'BOTANY', text: 'Biofertilizers include:', options: ['Rhizobium', 'Azotobacter', 'Blue-green algae', 'All of the above'] },
  { id: 'b15', number: 150, subject: 'BOTANY', text: 'The flocs formed during secondary treatment of sewage consist of:', options: ['Bacteria and fungal filaments', 'Algae and protozoa', 'Bacteria only', 'Protozoa only'] },
  { id: 'b16', number: 151, subject: 'BOTANY', text: 'Azotobacter is a:', options: ['Symbiotic nitrogen fixer', 'Free-living nitrogen fixer', 'Phosphate solubilizer', 'Pathogenic bacterium'] },
  { id: 'b17', number: 152, subject: 'BOTANY', text: 'The antibiotic streptomycin is obtained from:', options: ['Streptomyces griseus', 'Penicillium notatum', 'Bacillus subtilis', 'Aspergillus niger'] },
  { id: 'b18', number: 153, subject: 'BOTANY', text: 'Which of the following is used in bread making?', options: ['Lactobacillus', 'Saccharomyces cerevisiae', 'Acetobacter', 'Rhizopus'] },
  { id: 'b19', number: 154, subject: 'BOTANY', text: 'Vinegar is produced by:', options: ['Lactobacillus', 'Acetobacter aceti', 'Saccharomyces', 'Aspergillus'] },
  { id: 'b20', number: 155, subject: 'BOTANY', text: 'Blue-green algae used as biofertilizer in paddy fields is:', options: ['Anabaena', 'Nostoc', 'Oscillatoria', 'All of the above'] },
  { id: 'b21', number: 156, subject: 'BOTANY', text: 'The process of sewage treatment using microorganisms is called:', options: ['Bioremediation', 'Biodegradation', 'Bioaugmentation', 'All of the above'] },
  { id: 'b22', number: 157, subject: 'BOTANY', text: 'Citric acid is commercially produced using:', options: ['Aspergillus niger', 'Penicillium', 'Rhizopus', 'Mucor'] },
  { id: 'b23', number: 158, subject: 'BOTANY', text: 'The vaccine for hepatitis B is produced by:', options: ['Recombinant DNA technology', 'Tissue culture', 'Chemical synthesis', 'None of the above'] },
  { id: 'b24', number: 159, subject: 'BOTANY', text: 'Biogas mainly consists of:', options: ['Methane and CO₂', 'Methane and O₂', 'Ethane and CO₂', 'Propane and CO₂'] },
  { id: 'b25', number: 160, subject: 'BOTANY', text: 'Which microbe is used in single cell protein production?', options: ['Spirulina', 'Chlorella', 'Methylophilus', 'All of the above'] },
  // Organisms and Populations (161-180)
  { id: 'b26', number: 161, subject: 'BOTANY', text: 'An orchid growing on a mango tree is an example of:', options: ['Parasitism', 'Commensalism', 'Mutualism', 'Predation'] },
  { id: 'b27', number: 162, subject: 'BOTANY', text: 'The population growth curve that follows a sigmoid pattern is called:', options: ['J-shaped curve', 'S-shaped curve', 'Linear curve', 'Exponential curve'] },
  { id: 'b28', number: 163, subject: 'BOTANY', text: 'Which of the following is NOT a characteristic of r-selected species?', options: ['High reproductive rate', 'Small body size', 'Parental care', 'Short life span'] },
  { id: 'b29', number: 164, subject: 'BOTANY', text: 'The term "niche" was coined by:', options: ['Charles Elton', 'G.F. Gause', 'E.P. Odum', 'Joseph Grinnell'] },
  { id: 'b30', number: 165, subject: 'BOTANY', text: 'Competitive exclusion principle was given by:', options: ['Darwin', 'Gause', 'Elton', 'Odum'] },
  { id: 'b31', number: 166, subject: 'BOTANY', text: 'The type of interaction where one species benefits and the other is neither benefited nor harmed is:', options: ['Mutualism', 'Parasitism', 'Commensalism', 'Amensalism'] },
  { id: 'b32', number: 167, subject: 'BOTANY', text: 'Lichens are an example of:', options: ['Parasitism', 'Commensalism', 'Mutualism', 'Competition'] },
  { id: 'b33', number: 168, subject: 'BOTANY', text: 'The carrying capacity of an environment is represented by:', options: ['K', 'r', 'N', 'B'] },
  { id: 'b34', number: 169, subject: 'BOTANY', text: 'Brood parasitism is observed in:', options: ['Cuckoo', 'Crow', 'Sparrow', 'Pigeon'] },
  { id: 'b35', number: 170, subject: 'BOTANY', text: 'The study of population and its dynamics is called:', options: ['Ecology', 'Demography', 'Ethology', 'Genetics'] },
  { id: 'b36', number: 171, subject: 'BOTANY', text: 'Age pyramids with broad base indicate:', options: ['Stable population', 'Declining population', 'Expanding population', 'Zero growth population'] },
  { id: 'b37', number: 172, subject: 'BOTANY', text: 'Camouflage is an example of:', options: ['Adaptation to avoid predators', 'Mimicry', 'Warning coloration', 'Aposematism'] },
  { id: 'b38', number: 173, subject: 'BOTANY', text: 'Which of the following adaptations helps desert plants survive?', options: ['Thick cuticle', 'Sunken stomata', 'CAM pathway', 'All of the above'] },
  { id: 'b39', number: 174, subject: 'BOTANY', text: 'Migration in birds is primarily triggered by:', options: ['Temperature change', 'Photoperiod', 'Humidity', 'Wind direction'] },
  { id: 'b40', number: 175, subject: 'BOTANY', text: 'In exponential growth, the equation for population growth is:', options: ['dN/dt = rN', 'dN/dt = rN(K-N)/K', 'N = K', 'r = N/K'] },
  { id: 'b41', number: 176, subject: 'BOTANY', text: 'Aestivation is:', options: ['Winter sleep', 'Summer sleep', 'Daily sleep', 'Night activity'] },
  { id: 'b42', number: 177, subject: 'BOTANY', text: 'Which of the following is a density-independent factor?', options: ['Competition', 'Predation', 'Flood', 'Disease'] },
  { id: 'b43', number: 178, subject: 'BOTANY', text: 'Mycorrhizal association represents:', options: ['Parasitism', 'Mutualism', 'Commensalism', 'Amensalism'] },
  { id: 'b44', number: 179, subject: 'BOTANY', text: 'Natality refers to:', options: ['Death rate', 'Birth rate', 'Immigration rate', 'Emigration rate'] },
  { id: 'b45', number: 180, subject: 'BOTANY', text: 'The interaction between sea anemone and clown fish is:', options: ['Parasitism', 'Commensalism', 'Mutualism', 'Competition'] },
];

export const allQuestions: Question[] = [
  ...physicsQuestions,
  ...chemistryQuestions,
  ...zoologyQuestions,
  ...botanyQuestions,
];
